apiVersion: v1
kind: Secret
metadata:
  name: uptime-kuma-credentials
  namespace: uptime-operator
type: Opaque
data:
  username: YWRtaW4=  # admin (base64)
  password: YWRtaW4=  # admin (base64)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-operator
  namespace: uptime-operator
  labels:
    app: uptime-operator
    version: v1alpha1
spec:
  replicas: 1
  strategy:
    type: Recreate  # Only one instance should run at a time
  selector:
    matchLabels:
      app: uptime-operator
  template:
    metadata:
      labels:
        app: uptime-operator
    spec:
      serviceAccountName: uptime-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: operator
        image: uptime-operator:latest
        imagePullPolicy: Always
        env:
        - name: UPTIME_KUMA_URL
          value: "http://uptime-kuma.uptime-kuma:3001"  # Adjust to your Uptime Kuma service
        - name: UPTIME_KUMA_USERNAME
          valueFrom:
            secretKeyRef:
              name: uptime-kuma-credentials
              key: username
        - name: UPTIME_KUMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: uptime-kuma-credentials
              key: password
        - name: CLUSTER_NAME
          value: "production"  # Change to your cluster name
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-operator
  namespace: uptime-operator
  labels:
    app: uptime-operator
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: uptime-operator
